language: python
dist: xenial
sudo: required
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
addons:
  apt:
    sources: ['ubuntu-toolchain-r-test']
    packages: ['bash', 'coreutils']
cache:
  directories:
    - /home/travis/.cache/pip
before_install:
  - pip install pipenv==2018.11.26
  - pip install codecov==2.0.22
script:
  - python setup.py test
after_success:
  - codecov

